version: '3.3'

services:
  exceldb:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: excel
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  excel:
    depends_on:
      - exceldb
    image: wordpress:latest
    build:      
      context: ./docker
      dockerfile: wordpress.dockerfile
    expose:
      - 443
    restart: always
    environment:
      WORDPRESS_DB_HOST: exceldb:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: excel
      VIRTUAL_HOST: excel.dev
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: HTTPS      
    volumes:
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - exceldb:db
    ports:
      - 8002:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: exceldb
      
#volumes:
#    db_data: {}

networks:
  default:
    external:
      name: nginx-proxy

