version: 2.1

defaults: &defaults
    docker:
        - image: circleci/node:10.13.0
    working_directory: ~/excel

jobs:
    build:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                key: yarn-cache-{{ checksum "~/excel/wp-content/themes/excel2018/yarn.lock" }}

            - restore_cache:
                key: node-modules-{{ checksum "~/excel/wp-content/themes/excel2018/yarn.lock" }}

            - run:
                name: Install Dependencies
                working_directory: ~/excel/wp-content/themes/excel2018
                command: |
                    yarn install

            - save_cache:
                key: yarn-cache-{{ checksum "~/excel/wp-content/themes/excel2018/yarn.lock" }}
                paths:
                    - ~/.cache/yarn

            - save_cache:
                key: node-modules-{{ checksum "~/excel/wp-content/themes/excel2018/yarn.lock" }}
                paths:
                    - ~/excel/wp-content/themes/excel2018/node_modules

            - run:
                name: Build
                working_directory: ~/excel/wp-content/themes/excel2018
                command: |
                    yarn build

            - run:
                name: Update .gitignore files
                command: |
                    find `pwd` -name '.gitignore' -print0 | while IFS= read -r -d $'\0' file; do
                        echo $file
                        sed -i -e 's/# ::: //g' $file
                        sed -i -e '/.*::: cut :::*/,$d' $file
                    done

            - persist_to_workspace:
                root: ~/excel
                paths: .

    deploy_production_OFFLINE:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/excel

            - deploy:
                command: |
                    git config --global user.email "george@hotsauceatl.com"
                    git config --global user.name "Hot Sauce [circleci]"
                    git clone https://DISABLEDexcel:${livepass}@pdgmpro.com/plesk-git/pdgmpro.git tmp_remote
                    rm -rf .git
                    mv tmp_remote/.git .git
                    rm -rf tmp_remote
                    git add -A
                    git commit -m"deploy"
                    git push -o nolint origin master

    deploy_stage:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/excel

            - deploy:
                command: |
                    git config --global user.email "george@hotsauceatl.com"
                    git config --global user.name "Hot Sauce [circleci]"
                    git clone https://hotsauce:${stagepass}@excel-health.hotsauceatl.com/plesk-git/excel-health.git tmp_remote
                    rm -rf .git
                    mv tmp_remote/.git .git
                    rm -rf tmp_remote
                    git add -A
                    git commit -m"deploy"
                    git push -o nolint origin master

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy_stage:
                requires:
                    - build
                filters:
                    branches:
                        only: master
